# See: https://yamllint.readthedocs.io/en/stable/
rules:
  document-end: disable
  document-start: disable
  line-length:
    level: warning
    max: 80
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  bracket-spacing: 1
ignore:
  - .licenses/
