---
extends: default

# See: https://yamllint.readthedocs.io/en/stable/
rules:
  document-end: disable
  document-start: disable
  line-length:
    level: warning
    max: 80
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  bracket-spacing: 1
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']

ignore: |
  dist/
  coverage/
  node_modules/
  stryker-tmp/
