---
name: TypeScript Tests
on:
  workflow_call:
    outputs:
      test-status:
        description: 'Status of the tests'
        value: ${{ jobs.test.outputs.status }}

jobs:
  test:
    name: Run TypeScript Tests
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set-output.outputs.status }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/workflows/reusable/setup-node.yaml
        with:
          node-version-file: .node-version

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - name: Mutation Test
        id: npm-mutation-test
        run: npm run test:mutation

      - name: Set Output
        id: set-output
        run: echo "status=success" >> $GITHUB_OUTPUT
