name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop
      - release/**
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    uses: ./.github/workflows/typescript-test.yaml

  lint:
    name: Lint Code
    uses: ./.github/workflows/lint.yaml

  check-dist:
    name: Check dist
    uses: ./.github/workflows/check-dist.yaml

  test-action:
    name: Mutation Test
    uses: ./.github/workflows/mutation-test.yaml
