name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop
      - release/**
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

# Skip this workflow for automated version bump PRs
jobs:
  check-labels:
    name: Check PR Labels
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check-labels.outputs.should_skip }}
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    steps:
      - name: Check for no-deploy label
        id: check-labels
        run: |
          echo "Checking for no-deploy label on PR #${{ github.event.pull_request.number }}"

          # Get PR labels
          LABELS=$(curl -s -H "Authorization: token $DEPLOY_KEY" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
            | jq -r '.[].name')

          # Check if no-deploy label exists
          if echo "$LABELS" | grep -q "no-deploy"; then
            echo "PR has no-deploy label, skipping workflow"
            echo "should_skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "PR does not have no-deploy label, continuing workflow"
            echo "should_skip=false" >> "$GITHUB_OUTPUT"
          fi

  test-typescript:
    name: TypeScript Tests
    needs: check-labels
    if: needs.check-labels.outputs.should_skip != 'true'
    uses: ./.github/workflows/typescript-test.yaml

  lint:
    name: Lint Code
    needs: check-labels
    if: needs.check-labels.outputs.should_skip != 'true'
    uses: ./.github/workflows/lint.yaml

  check-dist:
    name: Check dist
    needs: check-labels
    if: needs.check-labels.outputs.should_skip != 'true'
    uses: ./.github/workflows/check-dist.yaml

  test-action:
    name: Mutation Test
    needs: check-labels
    if: needs.check-labels.outputs.should_skip != 'true'
    uses: ./.github/workflows/mutation-test.yaml
