name: TypeScript Tests
on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Run TypeScript Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: ./.github/workflows/setup-node.yaml
        with:
          node-version-file: '20'

      - name: Check Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run ci-test

      - name: Mutation Test
        run: npm run test:mutation
